---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provisioning EC2 Linux Instance
Parameters:
  KeyName:
    Description: Key Pair that needs to be used for the instance creation
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType: 
    Description: This is my First Linux server via Cloud Formation Template
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m5.xlarge
      - c5.2xlarge
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: "ami-0947d2ba12ee1ff75"
